services:
  - type: web
    name: jp-vocab-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
